List goChickenSaleStoreData = [
  {
    "storeNum": 1,
    "storeName": "BHC",
    "storeBranch": 1950,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 2,
    "storeName": "BBQ",
    "storeBranch": 1559,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 3,
    "storeName": "맘스터치",
    "storeBranch": 1406,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 4,
    "storeName": "처갓집양념치킨",
    "storeBranch": 1184,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 5,
    "storeName": "교촌치킨",
    "storeBranch": 1149,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 6,
    "storeName": "굽네치킨",
    "storeBranch": 1125,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 7,
    "storeName": "네네치킨",
    "storeBranch": 1096,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 8,
    "storeName": "페리카나",
    "storeBranch": 1085,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 9,
    "storeName": "호식이두마리치킨",
    "storeBranch": 823,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 10,
    "storeName": "푸라닭치킨",
    "storeBranch": 730,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 11,
    "storeName": "지코바양념치킨",
    "storeBranch": 712,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 12,
    "storeName": "자담치킨",
    "storeBranch": 711,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 13,
    "storeName": "60계",
    "storeBranch": 662,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 14,
    "storeName": "멕시카나",
    "storeBranch": 638,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 15,
    "storeName": "노랑통닭",
    "storeBranch": 624,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 16,
    "storeName": "가마치통닭",
    "storeBranch": 586,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 17,
    "storeName": "또래오래",
    "storeBranch": 511,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 18,
    "storeName": "피자나라치킨공주",
    "storeBranch": 491,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 19,
    "storeName": "또봉이통닭",
    "storeBranch": 474,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 20,
    "storeName": "맥시칸치킨",
    "storeBranch": 434,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 21,
    "storeName": "치킨플러스",
    "storeBranch": 339,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 22,
    "storeName": "코리엔탈깻잎두마리치킨",
    "storeBranch": 327,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 23,
    "storeName": "훌랄라참숯치킨",
    "storeBranch": 320,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 24,
    "storeName": "티바두마리치킨",
    "storeBranch": 307,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 25,
    "storeName": "부어치킨",
    "storeBranch": 285,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 26,
    "storeName": "바른치킨",
    "storeBranch": 282,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 27,
    "storeName": "후라이드참잘하는집",
    "storeBranch": 266,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 28,
    "storeName": "땅땅치킨",
    "storeBranch": 254,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 29,
    "storeName": "누구나홀딱반한닭",
    "storeBranch": 235,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 30,
    "storeName": "순살만공격",
    "storeBranch": 218,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 31,
    "storeName": "치킨마루",
    "storeBranch": 202,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 32,
    "storeName": "꾸브라꼬숯불두마리치킨",
    "storeBranch": 198,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 33,
    "storeName": "이경규의돈치킨",
    "storeBranch": 193,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 34,
    "storeName": "KFC",
    "storeBranch": 189,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 35,
    "storeName": "보드람치킨",
    "storeBranch": 185,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 36,
    "storeName": "깐부치킨",
    "storeBranch": 183,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 37,
    "storeName": "신통치킨",
    "storeBranch": 170,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 38,
    "storeName": "아라치",
    "storeBranch": 166,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 39,
    "storeName": "동근이숯불두마리치킨",
    "storeBranch": 164,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 40,
    "storeName": "순살몬스터",
    "storeBranch": 164,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 41,
    "storeName": "인생닭강정",
    "storeBranch": 163,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 42,
    "storeName": "치킨신드롬",
    "storeBranch": 161,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 43,
    "storeName": "알통떡강정",
    "storeBranch": 159,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 44,
    "storeName": "걸작떡볶이치킨",
    "storeBranch": 156,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 45,
    "storeName": "치꼬뱅",
    "storeBranch": 152,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 46,
    "storeName": "불로만치킨바베큐",
    "storeBranch": 151,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 47,
    "storeName": "치킨과바람피자",
    "storeBranch": 151,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 48,
    "storeName": "호치킨",
    "storeBranch": 148,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 49,
    "storeName": "오븐마루치킨",
    "storeBranch": 147,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 50,
    "storeName": "치킨매니아",
    "storeBranch": 146,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 51,
    "storeName": "가마로강정",
    "storeBranch": 137,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 52,
    "storeName": "기영이숯불두마리치킨",
    "storeBranch": 136,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 53,
    "storeName": "계동치킨",
    "storeBranch": 136,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 54,
    "storeName": "맛닭꼬",
    "storeBranch": 127,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 55,
    "storeName": "장모님치킨",
    "storeBranch": 121,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 56,
    "storeName": "썬더치킨",
    "storeBranch": 120,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 57,
    "storeName": "명가통닭",
    "storeBranch": 117,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 58,
    "storeName": "디디치킨",
    "storeBranch": 116,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 59,
    "storeName": "본스치킨",
    "storeBranch": 112,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 60,
    "storeName": "치킨더홈",
    "storeBranch": 112,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 61,
    "storeName": "코리안바베큐",
    "storeBranch": 112,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 62,
    "storeName": "오븐에꾸운닭",
    "storeBranch": 111,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 63,
    "storeName": "DK동키치킨",
    "storeBranch": 104,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 64,
    "storeName": "이춘봉치킨",
    "storeBranch": 101,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 65,
    "storeName": "순수치킨",
    "storeBranch": 100,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 66,
    "storeName": "충만치킨",
    "storeBranch": 99,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 67,
    "storeName": "다사랑",
    "storeBranch": 94,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 68,
    "storeName": "양계장집아들",
    "storeBranch": 90,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 69,
    "storeName": "바보스",
    "storeBranch": 88,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 70,
    "storeName": "투존치킨",
    "storeBranch": 87,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 71,
    "storeName": "둘둘치킨",
    "storeBranch": 82,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 72,
    "storeName": "남다른썬치킨",
    "storeBranch": 82,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 73,
    "storeName": "오태식해바라기치킨",
    "storeBranch": 80,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 74,
    "storeName": "냠냠숯불두마리치킨",
    "storeBranch": 80,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 75,
    "storeName": "림스치킨",
    "storeBranch": 80,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 76,
    "storeName": "박군치킨",
    "storeBranch": 80,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 77,
    "storeName": "봉이치킨",
    "storeBranch": 79,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 78,
    "storeName": "치교치킨",
    "storeBranch": 79,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 79,
    "storeName": "오븐에빠진닭",
    "storeBranch": 78,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 80,
    "storeName": "오늘통닭",
    "storeBranch": 76,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 81,
    "storeName": "당신은지금치킨이땡긴다",
    "storeBranch": 75,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 82,
    "storeName": "미쳐버린파닭",
    "storeBranch": 72,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 83,
    "storeName": "화락바베큐치킨",
    "storeBranch": 70,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 84,
    "storeName": "국제통닭",
    "storeBranch": 70,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 85,
    "storeName": "쌀통닭",
    "storeBranch": 69,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 86,
    "storeName": "아주커",
    "storeBranch": 68,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 87,
    "storeName": "치킨678",
    "storeBranch": 67,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 88,
    "storeName": "치킨멤버",
    "storeBranch": 66,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 89,
    "storeName": "스모프치킨",
    "storeBranch": 65,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 90,
    "storeName": "아웃닭",
    "storeBranch": 62,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 91,
    "storeName": "짱닭치킨",
    "storeBranch": 61,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 92,
    "storeName": "경아두마리치킨",
    "storeBranch": 60,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 93,
    "storeName": "컬투치킨",
    "storeBranch": 60,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 94,
    "storeName": "두리아",
    "storeBranch": 59,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 95,
    "storeName": "수원왕갈비통닭",
    "storeBranch": 59,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 96,
    "storeName": "진미대왕통닭",
    "storeBranch": 58,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 97,
    "storeName": "사쿠사쿠",
    "storeBranch": 58,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 98,
    "storeName": "닭장수후라이드화",
    "storeBranch": 58,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 99,
    "storeName": "범프리카인생치킨",
    "storeBranch": 58,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 100,
    "storeName": "계림원누룽지통닭구이",
    "storeBranch": 57,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 101,
    "storeName": "치요남치킨",
    "storeBranch": 56,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 102,
    "storeName": "허갈닭강정",
    "storeBranch": 56,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 103,
    "storeName": "철인7호",
    "storeBranch": 56,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 104,
    "storeName": "한앤둘치킨",
    "storeBranch": 54,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 105,
    "storeName": "전설의치킨",
    "storeBranch": 53,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  }
  


];