List goChickenSaleStoreTop20Data = [
  {
    "storeNum": 1,
    "storeName": "BHC",
    "storeBranch": 1950,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 2,
    "storeName": "BBQ",
    "storeBranch": 1559,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 3,
    "storeName": "맘스터치",
    "storeBranch": 1406,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 4,
    "storeName": "처갓집양념치킨",
    "storeBranch": 1184,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 5,
    "storeName": "교촌치킨",
    "storeBranch": 1149,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 6,
    "storeName": "굽네치킨",
    "storeBranch": 1125,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 7,
    "storeName": "네네치킨",
    "storeBranch": 1096,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 8,
    "storeName": "페리카나",
    "storeBranch": 1085,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 9,
    "storeName": "호식이두마리치킨",
    "storeBranch": 823,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 10,
    "storeName": "푸라닭치킨",
    "storeBranch": 730,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 11,
    "storeName": "지코바양념치킨",
    "storeBranch": 712,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 12,
    "storeName": "자담치킨",
    "storeBranch": 711,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 13,
    "storeName": "60계",
    "storeBranch": 662,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 14,
    "storeName": "멕시카나",
    "storeBranch": 638,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 15,
    "storeName": "노랑통닭",
    "storeBranch": 624,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 16,
    "storeName": "가마치통닭",
    "storeBranch": 586,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 17,
    "storeName": "또래오래",
    "storeBranch": 511,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 18,
    "storeName": "피자나라치킨공주",
    "storeBranch": 491,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 19,
    "storeName": "또봉이통닭",
    "storeBranch": 474,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },
  {
    "storeNum": 20,
    "storeName": "맥시칸치킨",
    "storeBranch": 434,
    "today": false,
    "maxDiscount": 0,
    "deliveryMaxDiscount": 0,
    "pickUpMaxDiscount": 0,
    "favorite": false,
    "delivery": [],
    "pickUp": [],
    "saleInfo": [],
    "etc": "",
  },

];